import { route_con802 } from "./CON802";
import { route_serco } from "./COR101";
import { route_depco } from "./COR102";
import { route_tipco } from "./COR103";
import { route_auxtip } from "./COR104";
import { route_unifun } from "./COR105";
import { route_remidep } from "./COR106";
import { route_holding } from "./COR107";
import { route_cargops } from "./COR108";
import { route_corres } from "./COR201";
import { route_informeCorres } from "./COR301";
import { route_listadoRespuesta } from "./COR304";
import { route_macorr } from "./COR402";
import { route_usuvue } from "./USUVUE";
import { router_favoritos } from "./FAVORITOS";
import { router_config } from "./CONFIG";
import { router_modulos } from "./MODULOS";
import { route_corr864 } from "./CORR864";
import { route_corr868 } from "./CORR868";
import { route_corr869 } from "./CORR869";
import { route_corr871 } from "./CORR871";
import { route_corr881 } from "./CORR881";
import { route_corr891 } from "./CORR891";
import { router_dn_habil } from "./DNHABIL";
import {route_rescorr} from "./COR403";
import {route_usuar} from "./USUAR";
import { route_pruebaImp1M } from "./CORRPRU";
import {route_terce} from "./COR201C";
import { route_asigna_modul } from "./ASIGNAMODULOS"; 
import { route_image } from "./IMAGE";
// import {route_activ} from "./";
// import {route_ciuda} from "./";
// import {route_corres} from "./";

export const SERCO = route_serco;
export const DEPCO = route_depco;
export const TIPCO = route_tipco;
export const AUXTIP = route_auxtip;
export const UNIFUN = route_unifun;
export const REMIDEP = route_remidep;
export const HOLDING = route_holding;
export const CARGOPS = route_cargops;
export const CORRES = route_corres;
export const CON802 = route_con802;
export const CORRESINFOR = route_informeCorres;
export const CORRPRU = route_pruebaImp1M;
export const LISTADORESCORR = route_listadoRespuesta;
export const MACORR = route_macorr;
export const USUVUE = route_usuvue;
export const FAVORITOS = router_favoritos;
export const CONFIG = router_config;
export const MODULOS = router_modulos;
export const CORR864 = route_corr864;
export const CORR868 = route_corr868;
export const CORR869 = route_corr869;
export const CORR871 = route_corr871;
export const CORR881 = route_corr881;
export const CORR891 = route_corr891;
export const DNHABIL = router_dn_habil;
export const RESCORR = route_rescorr;
export const USUAR = route_usuar;
export const TERCE = route_terce;
export const ASIGNAMODULOS = route_asigna_modul;
export const IMAGE = route_image
// export const ACTIV = route_activ;
// export const CIUDA = route_ciuda;
// export const CORRES = route_corres;
